INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Race Director',3,0,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Scoring',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sign up/Tower Help (7am-4:30pm)',3,0,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Saturday Night Gate 5pm-10pm',1.5,NULL,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sunday Front Gate 6:45a - 3p',3,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sunday Front Gate 9a - 12a',1,NULL,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sunday Front Gate 7:30a - 10:30a',1,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sunday Front Gate 12-3',1,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Course Marshall/Sweeper  - Morning (7:30am - 12pm)',3,0,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Course Marshall/Sweeper - Afternoon (11:30am - 5pm)',3,0,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Facility Cleanup',1,NULL,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Monday Cleanup Crew',3,0,7,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('50cc Track - Sunday 9-3',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('President',3,150,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Scoring (front gate help first)',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Head Scorer/District Sign up',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Dist sign-up/Scoring',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Start Gate/Gate help',3,75,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Head Starter',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Mini Track Scoring',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Mini Track Head Guy/Starter',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Mini Track -Finish Line flagger/start gate',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Mini Track Flagger',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front Gate 8-12',1.5,0,5,0,0,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front/Back Gate 6:45am - 10am (scorer  - this job first)',0,0,6,1,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front/Back Gate 9-1',1.5,50,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front Gate 12-3',1,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Head Flagger',4,80,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 1 - Flyoff',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 2 - Step Up',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 3  -  Hill Top (Post Walker''s)',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 4 - Hartman''s Hill',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 5 - Leap',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 6 - Double Double',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 7 - Corner Table',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 8 - 10000 Gallon',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 10 - Cavity Out',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 12 - Pre-Finish Jump',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 13 - Finish Line',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Track Maintenance/Relief Flagger (roll up hose)',3,0,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Track Maintenance/Relief Flagger (MAIN) (roll up hose)',3,0,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Facility Clean up (garbage, signs, banners, road signs)',1,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('PeeWee Track Maintenance',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Bathroom Maintenance',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Announcer',3,250,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('ESMX Racing Ref',0,100,6,1,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sat. Front gate 3-7',1.5,0,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sat. Front gate 7-11',1.5,0,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('District Signup Saturday',0,40,5,1,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Saturday Signup 5p-7p',1,0,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Saturday Night Watering',2,0,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Friday Night Watering',2,0,4,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Rock Picking',2,0,2,0,0,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Scorer (front gate till 8:15)',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Scorer (office till 8:15)',3,125,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sign up (all day)',3,125,6,1,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Starter/Finish Flagger',4,150,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sweeper/Marshall (morning)',3,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger',4,80,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Relief Flagger',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front Gate Sunday Morning (7-2)',3,75,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front Gate Sunday Morning (8:15-3)',2,75,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Pee Wee Scoring',1,NULL,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Pee wee Finish Line flagger/start gate',2,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Vice President',3,150,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Treasurer',3,150,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Secretary',3,150,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Public Relations',3,150,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sign up/Main Scorer (all day)',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front Gate 6:45am - 3pm',2.5,100,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Friday Front gate 5-11',2,0,4,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Finish Line Flagger',3,75,5,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Start Gate/District Sign Up',3,125,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sign-Up/Tower Help',3,125,6,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 1 - Fly Off',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 2 - Step Up',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 3 - Hill Top (post Walker''s)',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 4 - Hartman''s Hill',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 5 - Leap',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 6 - Double Double',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 7 - Corner Table',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 8 - 10000 Gallon',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 9 - Cavity In',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 10 - Cavity Out',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 11 - Uphill Double',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 12 - Pre-Finish Jump',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 9 - Cavity In',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Signup/Tower',3,0,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sweeper/Marshall (afternoon)',3,0,6,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('EMS',0,600,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Pit Marshall',2,0,6,0,0,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Saturday Front Gate (2-5)',1,0,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Saturday Front Gate (5-10)',2,0,5,1,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Saturday - Relief Flagger/Floater',3,40,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sign Up/Tower Help',3,0,5,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Ambulance',0,400,5,1,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front Gate 8-3',3,0,5,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Practice Flagger 13 - Finish Line',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger - Flyoff',2.5,50,2,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Tuesday Night Watering',2,0,1,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Wednesday Morning Watering',2,0,2,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Sign Up: 1pm - 7:30pm',3,0,2,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('EMT',0,400,2,1,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Front Gate 12-6',3,NULL,2,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 14- Extra',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger 15 - Extra',4,80,6,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger - Extra 14',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Flagger - Extra 15',3,50,5,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Thursday Night Watering',2,0,NULL,0,1,0,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Start Gate Stager (Check transponders) (7:30am - 3pm)',2.5,0,NULL,0,0,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Course Marshall/Sweeper All day',5,0,NULL,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Office Help (6:45am - ?)',3,0,NULL,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Office Help (8am - 4pm)',2,0,NULL,0,1,1,1);
INSERT INTO job_type(title,point_value,cash_value,job_day_number,reserved,online,meal_ticket, active) VALUES ('Office Help (6:45am - ?)',1,0,NULL,0,1,1,1);
