insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2009, '88811 Moulton Pass', 'Flushing', 'NY', 48463);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2003, '25 Laurel Hill', 'North Las Vegas', 'NV', 59294);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2005, '1869 Mifflin Park', 'Gatesville', 'TX', 62140);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1985, '96 North Circle', 'Missoula', 'MT', 78375);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2007, '519 Moose Parkway', 'Lakeland', 'FL', 29390);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2010, '3 Cascade Park', 'Spartanburg', 'SC', 63909);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1995, '27210 Marquette Crossing', 'Macon', 'GA', 47725);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2006, '38 Pond Alley', 'Escondido', 'CA', 71492);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1969, '433 Jenifer Terrace', 'Portland', 'OR', 70029);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1988, '5329 Almo Road', 'Phoenix', 'AZ', 38220);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2001, '53 Anhalt Place', 'Annapolis', 'MD', 19808);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1998, '3 Mccormick Road', 'Phoenix', 'AZ', 40712);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1998, '501 Hoard Lane', 'Visalia', 'CA', 76425);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2010, '90 Melrose Trail', 'Fort Smith', 'AR', 21095);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1994, '4 Corben Parkway', 'Hollywood', 'FL', 89235);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1992, '14 Old Gate Circle', 'Madison', 'WI', 57320);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1994, '6993 Myrtle Lane', 'Gainesville', 'FL', 57900);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2006, '81345 Hauk Parkway', 'Sacramento', 'CA', 87748);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1992, '68 Miller Terrace', 'Greensboro', 'NC', 12999);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1992, '79344 Granby Court', 'Torrance', 'CA', 38646);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1996, '723 Forster Crossing', 'Charlotte', 'NC', 47578);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1999, '0 Sloan Trail', 'Jefferson City', 'MO', 33878);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1990, '1 Manufacturers Parkway', 'Des Moines', 'IA', 79207);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1997, '2 Roxbury Court', 'Odessa', 'TX', 18202);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1994, '376 Jackson Avenue', 'Davenport', 'IA', 78920);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1999, '80 Annamark Avenue', 'Garland', 'TX', 93169);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1998, '9350 Hoffman Crossing', 'Pueblo', 'CO', 39281);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2002, '540 Crest Line Hill', 'El Paso', 'TX', 71176);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1991, '1433 Independence Drive', 'Terre Haute', 'IN', 85082);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1987, '4524 Tennessee Avenue', 'Houston', 'TX', 21421);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2003, '12 Lotheville Court', 'Saint Joseph', 'MO', 46895);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1986, '7477 Waubesa Alley', 'Fort Smith', 'AR', 25756);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2007, '1740 Monument Avenue', 'New York City', 'NY', 92679);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2011, '7 Jay Lane', 'Paterson', 'NJ', 38333);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2005, '72 Debra Junction', 'Jacksonville', 'FL', 73994);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2012, '046 Merry Park', 'Rochester', 'NY', 47014);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2012, '4 Summit Way', 'Punta Gorda', 'FL', 69873);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2006, '1330 Hagan Hill', 'Santa Barbara', 'CA', 38358);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1987, '7084 Porter Junction', 'Clearwater', 'FL', 21605);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1993, '09494 Waxwing Street', 'Loretto', 'MN', 18480);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2001, '9 Comanche Circle', 'Valdosta', 'GA', 92807);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2011, '0898 Ilene Park', 'Rochester', 'NY', 54430);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2008, '46 East Hill', 'Albuquerque', 'NM', 26262);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2002, '0033 Ramsey Way', 'Saint Petersburg', 'FL', 11933);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2008, '426 Sommers Avenue', 'Knoxville', 'TN', 36998);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2010, '5061 Vera Drive', 'Louisville', 'KY', 63279);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2005, '78 Grim Place', 'Washington', 'DC', 70615);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1989, '47 Schurz Court', 'Greensboro', 'NC', 77605);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1990, '01 Farwell Parkway', 'Saint Cloud', 'MN', 67862);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1998, '5551 Division Court', 'Spring', 'TX', 83665);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1996, '61708 Troy Road', 'Colorado Springs', 'CO', 16043);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2002, '94209 Stang Hill', 'Boston', 'MA', 96924);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2000, '27935 Moland Parkway', 'Charlotte', 'NC', 21101);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1990, '487 Maryland Court', 'Los Angeles', 'CA', 98859);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1993, '21175 Bartillon Terrace', 'Sioux City', 'IA', 99259);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2000, '1259 Thompson Avenue', 'Troy', 'MI', 51651);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2001, '78 Thierer Place', 'Denver', 'CO', 48573);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2007, '978 Southridge Parkway', 'Santa Barbara', 'CA', 50071);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2004, '3 Ryan Parkway', 'Yakima', 'WA', 64887);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2007, '3 Jana Street', 'Louisville', 'KY', 44377);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1996, '57506 Hoffman Drive', 'Texarkana', 'TX', 74685);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2004, '412 Dennis Court', 'Fort Lauderdale', 'FL', 48877);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1995, '22 Lyons Point', 'Orange', 'CA', 69943);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1995, '77 Delaware Street', 'Lynchburg', 'VA', 21334);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2000, '137 Myrtle Circle', 'Dallas', 'TX', 89443);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1988, '03675 Maywood Hill', 'Meridian', 'MS', 39534);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1992, '7 American Pass', 'Norfolk', 'VA', 68746);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1999, '2972 Rowland Drive', 'New Orleans', 'LA', 31072);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2005, '0 Eastlawn Pass', 'El Paso', 'TX', 95808);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2003, '23 Summerview Place', 'Huntington', 'WV', 34228);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1967, '89964 Bluestem Road', 'Salt Lake City', 'UT', 24135);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1994, '4 Summer Ridge Alley', 'Lafayette', 'LA', 89884);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2002, '56107 Eagan Crossing', 'New York City', 'NY', 32950);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1984, '879 Buhler Lane', 'Tulsa', 'OK', 42897);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2008, '1 Fairview Park', 'Denton', 'TX', 79765);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2010, '6 Jay Hill', 'Roanoke', 'VA', 18698);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2004, '7470 Dovetail Court', 'Dayton', 'OH', 15303);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2012, '936 Dottie Center', 'Birmingham', 'AL', 54440);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2004, '3266 Brown Lane', 'Cape Coral', 'FL', 67695);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1992, '73 Hansons Drive', 'Warren', 'OH', 20801);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2009, '95 Golden Leaf Trail', 'Seattle', 'WA', 55095);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1996, '7 La Follette Place', 'Oklahoma City', 'OK', 79922);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2009, '17 Almo Circle', 'Washington', 'DC', 90392);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1993, '11722 Mifflin Center', 'Tampa', 'FL', 98575);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2000, '17 Dorton Pass', 'Bismarck', 'ND', 26076);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2005, '8839 Waxwing Point', 'Montgomery', 'AL', 29519);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1998, '88 Schurz Parkway', 'San Diego', 'CA', 76106);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2004, '4216 Caliangt Parkway', 'Louisville', 'KY', 61363);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2012, '7 Melrose Terrace', 'Canton', 'OH', 72007);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2007, '1829 Eagan Pass', 'Pittsburgh', 'PA', 44506);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2011, '1 Farragut Way', 'San Jose', 'CA', 61123);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2012, '2798 Cordelia Alley', 'El Paso', 'TX', 35301);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1980, '55239 Forster Hill', 'Atlanta', 'GA', 92893);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2011, '6 Mandrake Circle', 'Fargo', 'ND', 45775);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2007, '8768 Michigan Alley', 'Minneapolis', 'MN', 77253);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1981, '783 Elmside Parkway', 'Dallas', 'TX', 57503);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 2010, '70 North Junction', 'Joliet', 'IL', 65322);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1997, '7790 Novick Trail', 'Fort Lauderdale', 'FL', 70121);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1994, '0 Drewry Point', 'El Paso', 'TX', 22518);
insert into membership (active, cur_year_renewed, view_online, renewal_sent, year_joined, address, city, state, zip) values (1, 0, 1, 0, 1986, '007 Clemons Avenue', 'Billings', 'MT', 51182);